from enum import Enum

class SessionType(Enum):
    DAILY_PRACTICE = "DAILY_PRACTICE"
    TOPIC_REVISION = "TOPIC_REVISION"
    CHAPTER_REVISION = "CHAPTER_REVISION"
    REVISION = "REVISION"
    WEAK_POINT = "WEAK_POINT"
    EXAM_PREPARATION = "EXAM_PREPARATION"
    TEACHER_ASSIGNMENT = "TEACHER_ASSIGNMENT"
    CUSTOM = "CUSTOM"
    AI_RECOMMENDED = "AI_RECOMMENDED"
    
    # Legacy fallbacks
    RECOVERY = "RECOVERY"
    WEEKLY_REVIEW = "WEEKLY_REVIEW"
    MOCK_TEST = "MOCK_TEST"
    CHALLENGE = "CHALLENGE"

class SessionState(Enum):
    CREATED = "CREATED"
    GENERATED = "GENERATED"
    STARTED = "STARTED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    ABANDONED = "ABANDONED"
    EXPIRED = "EXPIRED"

class LearningContext(Enum):
    TODAY_SCHOOL_TOPIC = "TODAY_SCHOOL_TOPIC"
    EXAM_REVISION = "EXAM_REVISION"
    WEEKLY_REVISION = "WEEKLY_REVISION"
    REMEDIAL = "REMEDIAL"
