"""Add question intelligence metadata fields

Revision ID: 14177565f71b
Revises: 168d1185ce16
Create Date: 2026-07-13 14:30:04.059095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14177565f71b'
down_revision: Union[str, Sequence[str], None] = '168d1185ce16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('normalized_concept', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('cluster_name', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('question_purpose', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('progression_level', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('prerequisite_concepts', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('questions', sa.Column('misconception_tags', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'misconception_tags')
    op.drop_column('questions', 'prerequisite_concepts')
    op.drop_column('questions', 'progression_level')
    op.drop_column('questions', 'question_purpose')
    op.drop_column('questions', 'cluster_name')
    op.drop_column('questions', 'normalized_concept')
    # ### end Alembic commands ###
