"""add_student_xp_and_level

Revision ID: 6376fac27862
Revises: b201bb852f86
Create Date: 2026-07-15 13:34:54.017589+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6376fac27862'
down_revision: Union[str, None] = '591e8de84c24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('total_xp', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('students', sa.Column('current_level', sa.Integer(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('students', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('students', 'current_level')
    op.drop_column('students', 'total_xp')
    # ### end Alembic commands ###
