"""Add Learning Unit and Curriculum Hierarchy

Revision ID: 94e1c313635c
Revises: 1c9acad2dff0
Create Date: 2026-07-09 15:51:50.368850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '94e1c313635c'
down_revision: Union[str, Sequence[str], None] = '1c9acad2dff0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_boards_name'), 'boards', ['name'], unique=False)
    op.create_table('grades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('board_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grades_name'), 'grades', ['name'], unique=False)
    op.create_table('subjects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('grade_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subjects_name'), 'subjects', ['name'], unique=False)
    op.create_table('learning_units',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subtopic_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('learning_objective', sa.String(), nullable=False),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('estimated_reading_time', sa.Integer(), nullable=False),
    sa.Column('source_pages', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['subtopic_id'], ['subtopics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('chapters', sa.Column('subject_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'chapters', 'subjects', ['subject_id'], ['id'])
    op.add_column('questions', sa.Column('learning_unit_id', sa.UUID(), nullable=True))
    op.add_column('questions', sa.Column('learning_objective', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('questions', sa.Column('difficulty', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('estimated_time', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('hint_level_1', sa.Text(), nullable=True))
    op.add_column('questions', sa.Column('hint_level_2', sa.Text(), nullable=True))
    op.add_column('questions', sa.Column('full_explanation', sa.Text(), nullable=True))
    op.add_column('questions', sa.Column('source_pages', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('questions', sa.Column('supported_answer_modes', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('questions', sa.Column('expected_answer', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('acceptable_answers', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_constraint(op.f('questions_subtopic_id_fkey'), 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'learning_units', ['learning_unit_id'], ['id'])
    op.drop_column('questions', 'subtopic_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('subtopic_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key(op.f('questions_subtopic_id_fkey'), 'questions', 'subtopics', ['subtopic_id'], ['id'])
    op.drop_column('questions', 'acceptable_answers')
    op.drop_column('questions', 'expected_answer')
    op.drop_column('questions', 'supported_answer_modes')
    op.drop_column('questions', 'source_pages')
    op.drop_column('questions', 'full_explanation')
    op.drop_column('questions', 'hint_level_2')
    op.drop_column('questions', 'hint_level_1')
    op.drop_column('questions', 'estimated_time')
    op.drop_column('questions', 'difficulty')
    op.drop_column('questions', 'keywords')
    op.drop_column('questions', 'learning_objective')
    op.drop_column('questions', 'learning_unit_id')
    op.drop_constraint(None, 'chapters', type_='foreignkey')
    op.drop_column('chapters', 'subject_id')
    op.drop_table('learning_units')
    op.drop_index(op.f('ix_subjects_name'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_grades_name'), table_name='grades')
    op.drop_table('grades')
    op.drop_index(op.f('ix_boards_name'), table_name='boards')
    op.drop_table('boards')
    # ### end Alembic commands ###
