"""Add question intelligence fields

Revision ID: a674345cd788
Revises: 9e54f25d4c4f
Create Date: 2026-07-13 11:04:31.792523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a674345cd788'
down_revision: Union[str, Sequence[str], None] = '9e54f25d4c4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('question_hash', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('bloom_level', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('cognitive_level', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('intent', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('voice_score', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('speaking_time', sa.Float(), nullable=True))
    op.add_column('questions', sa.Column('thinking_time', sa.Float(), nullable=True))
    op.add_column('questions', sa.Column('cluster_id', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('session_tags', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('questions', sa.Column('production_score', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('coverage_weight', sa.Float(), nullable=True))
    op.add_column('questions', sa.Column('metadata_score', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'questions', ['question_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='unique')
    op.drop_column('questions', 'metadata_score')
    op.drop_column('questions', 'coverage_weight')
    op.drop_column('questions', 'production_score')
    op.drop_column('questions', 'session_tags')
    op.drop_column('questions', 'cluster_id')
    op.drop_column('questions', 'thinking_time')
    op.drop_column('questions', 'speaking_time')
    op.drop_column('questions', 'voice_score')
    op.drop_column('questions', 'intent')
    op.drop_column('questions', 'cognitive_level')
    op.drop_column('questions', 'bloom_level')
    op.drop_column('questions', 'question_hash')
    # ### end Alembic commands ###
