"""add runtime intelligence models final schema

Revision ID: b75e95c29369
Revises: 14177565f71b
Create Date: 2026-07-14 11:57:17.846642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b75e95c29369'
down_revision: Union[str, Sequence[str], None] = '14177565f71b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_name', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('correlation_id', sa.String(), nullable=True),
    sa.Column('causation_id', sa.String(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_log_correlation_id'), 'events_log', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_events_log_entity_id'), 'events_log', ['entity_id'], unique=False)
    op.create_index(op.f('ix_events_log_event_name'), 'events_log', ['event_name'], unique=False)
    op.create_index(op.f('ix_events_log_occurred_at'), 'events_log', ['occurred_at'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('grade_id', sa.UUID(), nullable=True),
    sa.Column('board_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('streak_days', sa.Integer(), nullable=False),
    sa.Column('total_study_minutes', sa.Integer(), nullable=False),
    sa.Column('overall_mastery_percentage', sa.Float(), nullable=False),
    sa.Column('overall_confidence_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learning_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('session_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('questions_requested', sa.Integer(), nullable=False),
    sa.Column('questions_answered', sa.Integer(), nullable=False),
    sa.Column('questions_correct', sa.Integer(), nullable=False),
    sa.Column('questions_skipped', sa.Integer(), nullable=False),
    sa.Column('average_response_time', sa.Float(), nullable=False),
    sa.Column('average_voice_score', sa.Float(), nullable=False),
    sa.Column('completion_reason', sa.String(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('mastery_gain', sa.Float(), nullable=False),
    sa.Column('weak_concepts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('strong_concepts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('session_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('voice_enabled', sa.Boolean(), nullable=False),
    sa.Column('difficulty_preference', sa.String(), nullable=False),
    sa.Column('daily_goal', sa.Integer(), nullable=False),
    sa.Column('notification_time', sa.String(), nullable=True),
    sa.Column('preferred_scheduler', sa.String(), nullable=False),
    sa.Column('theme', sa.String(), nullable=False),
    sa.Column('parent_mode', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_table('recommendation_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('recommendation_source', sa.String(), nullable=False),
    sa.Column('recommendation_reason', sa.String(), nullable=False),
    sa.Column('recommendation_priority', sa.String(), nullable=False),
    sa.Column('target_learning_unit_id', sa.UUID(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completion_status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['learning_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('concepts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('learning_unit_id', sa.UUID(), nullable=False),
    sa.Column('normalized_name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['learning_unit_id'], ['learning_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concepts_normalized_name'), 'concepts', ['normalized_name'], unique=False)
    op.create_table('question_analytics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('total_attempts', sa.Integer(), nullable=False),
    sa.Column('accuracy_rate', sa.Float(), nullable=False),
    sa.Column('skip_rate', sa.Float(), nullable=False),
    sa.Column('difficulty_index', sa.Float(), nullable=False),
    sa.Column('discrimination_index', sa.Float(), nullable=False),
    sa.Column('retirement_score', sa.Float(), nullable=False),
    sa.Column('average_response_time', sa.Float(), nullable=False),
    sa.Column('average_hint_usage', sa.Float(), nullable=False),
    sa.Column('average_voice_score', sa.Float(), nullable=False),
    sa.Column('rolling_30_day_accuracy', sa.Float(), nullable=False),
    sa.Column('rolling_90_day_accuracy', sa.Float(), nullable=False),
    sa.Column('last_attempted', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id')
    )
    op.create_table('question_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_from', sa.UUID(), nullable=True),
    sa.Column('change_reason', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_from'], ['question_versions.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_mastery',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('concept_id', sa.UUID(), nullable=False),
    sa.Column('learning_objective_id', sa.UUID(), nullable=True),
    sa.Column('mastery_percentage', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('wrong_count', sa.Integer(), nullable=False),
    sa.Column('last_practiced', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_student_mastery_student_concept', 'student_mastery', ['student_id', 'concept_id'], unique=True)
    op.create_index('ix_student_mastery_student_lo', 'student_mastery', ['student_id', 'learning_objective_id'], unique=True)
    op.create_table('student_responses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('expected_answer', sa.Text(), nullable=True),
    sa.Column('matched_answer', sa.Text(), nullable=True),
    sa.Column('evaluation_method', sa.String(), nullable=True),
    sa.Column('evaluation_score', sa.Float(), nullable=True),
    sa.Column('voice_transcript', sa.Text(), nullable=True),
    sa.Column('device_type', sa.String(), nullable=True),
    sa.Column('provided_answer', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('time_taken_seconds', sa.Float(), nullable=False),
    sa.Column('voice_score', sa.Float(), nullable=True),
    sa.Column('hints_used', sa.Integer(), nullable=False),
    sa.Column('confidence_rating', sa.Float(), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('assigned_difficulty', sa.Float(), nullable=True),
    sa.Column('question_difficulty', sa.Float(), nullable=True),
    sa.Column('student_difficulty', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['learning_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_review_schedule',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('concept_id', sa.UUID(), nullable=False),
    sa.Column('scheduler_type', sa.String(), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_review', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('successive_correct_reviews', sa.Integer(), nullable=False),
    sa.Column('scheduler_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('interval', sa.Float(), nullable=False),
    sa.Column('ease_factor', sa.Float(), nullable=False),
    sa.Column('stability', sa.Float(), nullable=False),
    sa.Column('difficulty', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_review_schedule_next_review'), 'student_review_schedule', ['next_review'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_review_schedule_next_review'), table_name='student_review_schedule')
    op.drop_table('student_review_schedule')
    op.drop_table('student_responses')
    op.drop_index('ix_student_mastery_student_lo', table_name='student_mastery')
    op.drop_index('ix_student_mastery_student_concept', table_name='student_mastery')
    op.drop_table('student_mastery')
    op.drop_table('question_versions')
    op.drop_table('question_analytics')
    op.drop_index(op.f('ix_concepts_normalized_name'), table_name='concepts')
    op.drop_table('concepts')
    op.drop_table('recommendation_history')
    op.drop_table('student_preferences')
    op.drop_table('learning_sessions')
    op.drop_table('students')
    op.drop_index(op.f('ix_events_log_occurred_at'), table_name='events_log')
    op.drop_index(op.f('ix_events_log_event_name'), table_name='events_log')
    op.drop_index(op.f('ix_events_log_entity_id'), table_name='events_log')
    op.drop_index(op.f('ix_events_log_correlation_id'), table_name='events_log')
    op.drop_table('events_log')
    # ### end Alembic commands ###
