"""update question schema for voice architecture

Revision ID: b88785527a8f
Revises: 94e1c313635c
Create Date: 2026-07-10 12:29:26.695425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b88785527a8f'
down_revision: Union[str, Sequence[str], None] = '94e1c313635c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('question_type', sa.String(), server_default='Concept', nullable=False))
    op.add_column('questions', sa.Column('mcq_options', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('questions', sa.Column('answer_complexity', sa.String(), server_default='WORD', nullable=False))
    op.alter_column('questions', 'correct_option',
               existing_type=sa.VARCHAR(length=1),
               nullable=True)
    op.drop_column('questions', 'option_c')
    op.drop_column('questions', 'option_d')
    op.drop_column('questions', 'option_b')
    op.drop_column('questions', 'option_a')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('option_a', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('questions', sa.Column('option_b', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('questions', sa.Column('option_d', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('questions', sa.Column('option_c', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('questions', 'correct_option',
               existing_type=sa.VARCHAR(length=1),
               nullable=False)
    op.drop_column('questions', 'answer_complexity')
    op.drop_column('questions', 'mcq_options')
    op.drop_column('questions', 'question_type')
    # ### end Alembic commands ###
