from enum import Enum

class EventName(str, Enum):
    QUESTION_ANSWERED = "QUESTION_ANSWERED"
    QUESTION_SKIPPED = "QUESTION_SKIPPED"
    HINT_USED = "HINT_USED"
    VOICE_SUBMITTED = "VOICE_SUBMITTED"
    SESSION_STARTED = "SESSION_STARTED"
    SESSION_FINISHED = "SESSION_FINISHED"
    MASTERY_UPDATED = "MASTERY_UPDATED"
    REVIEW_SCHEDULED = "REVIEW_SCHEDULED"
    RECOMMENDATION_CREATED = "RECOMMENDATION_CREATED"

class EntityType(str, Enum):
    STUDENT = "STUDENT"
    SESSION = "SESSION"
    QUESTION = "QUESTION"
    CONCEPT = "CONCEPT"
